# Generated by Django 6.0.5 on 2026-05-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='eggs_count',
            field=models.IntegerField(default=0, verbose_name='Eggs balance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_daily_tasks_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tickets_count',
            field=models.IntegerField(default=0, verbose_name='Tickets'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='today_eggs_count',
            field=models.IntegerField(default=0, verbose_name='Eggs earned today'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='today_eggs_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last reset date for today eggs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_eggs_count',
            field=models.IntegerField(default=0, verbose_name='Total eggs earned'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo_url',
            field=models.URLField(blank=True, default='', verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
