# Generated by Django 6.0.5 on 2026-05-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityaccess',
            old_name='has_access',
            new_name='has_community_access',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price_in_eggs',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='instantgift',
            name='eggs_reward',
        ),
        migrations.RemoveField(
            model_name='price',
            name='description',
        ),
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.AddField(
            model_name='instantgift',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instantgift',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instantgift',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='price',
            name='setting_type',
            field=models.CharField(choices=[('TICKET_PRICE', 'Ticket Price'), ('INSTANT_GIFT_PRICE', 'Instant Gift Price'), ('COMMUNITY_ENTRY_PRICE', 'Community Entry Price')], default='TICKET_PRICE', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
